name: ai-example

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run all:action
      - name: Modify reports
        run: npm run modify-reports
      - name: Publish Test Report
        uses: ./
        with:
          report-path: './ctrf-reports/*.json'
          ai-report: true
          upload-artifact: true
        if: always()