name: cli

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build:npm
      - name: Summary table
        run: node dist/core/cli.js summary ctrf-reports/ctrf-report.json --title "Summary table"
      - name: Default tables
        run: node dist/core/cli.js ctrf-reports/ctrf-report.json --title "Default tables"
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: ctrf-report
          path: ctrf-reports/ctrf-report.json
