name: detailed

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npx tsc
      - name: Test detailed with title
        run: node dist/index.js tests ctrf-reports/ctrf-report.json --exit-on-fail
        if: always()
      - name: Test default no title
        run: node dist/index.js ctrf-reports/ctrf-report.json --annotate false --exit-on-fail
        if: always()
      - name: Test skipped with title
        run: node dist/index.js skipped ctrf-reports/ctrf-report.json --exit-on-fail
        if: always()
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: ctrf-report
          path: ctrf-reports/ctrf-report.json
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: custom-artifact-name
          path: ctrf-reports/ctrf-report-no-fails.json
