name: failed-example

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Failed table
        run: node dist/core/cli.js failed ctrf-reports/ctrf-report.json --title "Failed table"
      - name: Failed folded
        run: node dist/core/cli.js failed-folded ctrf-reports/ctrf-report.json --title "Failed Folded" --annotate false
      - name: Fail rate table
        run: node dist/core/cli.js failed-rate ctrf-reports/ctrf-report.json --title "Fail rate table" --annotate false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fail rate max results
        run: node dist/core/cli.js failed-rate ctrf-reports/ctrf-report.json --title "Fail rate table max results 2" --results 2 --annotate false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fail rate table custom artifact name
        run: node dist/core/cli.js failed-rate ctrf-reports/ctrf-report-no-fails.json --annotate false --title "Flaky rate table custom artifact name" --artifact-name custom-artifact-name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: ctrf-report
          path: ctrf-reports/ctrf-report.json
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: custom-artifact-name
          path: ctrf-reports/ctrf-report-no-fails.json
