name: Use Markdown Summary

on: [push]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Specify the Node.js version you need

    - name: Install Dependencies
      run: npm install

    - name: Run CTRF annotations
      run: npx github-actions-ctrf all ctrf-report.json
    # Repeat similar for other commands

