name: Test summary example

on:
  push:
    branches:
      - main 
  schedule:
    - cron: '0 2 * * *'  
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: build
      run: npx tsc
    - name: Run index.js
      run: node dist/index.js ctrf-report.json