name: Use Markdown Summary

on: [push]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: build
      run: npx tsc
    - name: Run index.js
      run: node dist/index.js ctrf-report.json