name: main

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 2 * * *'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run all:action
      - name: Publish Test Report
        uses: ./
        with:
          report-path: './ctrf-reports/*.json'
          template-path: 'templates/custom-report.hbs'
          summary-report: true
          previous-results-report: true
          suite-folded-report: true
          failed-report: true
          fail-rate-report: true
          failed-folded-report: true
          flaky-report: true
          flaky-rate-report: true
          ai-report: true
          skipped-report: true
          custom-report: true
          upload-artifact: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
