name: main

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 2 * * *'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npx tsc
      - name: Test summary
        run: node dist/core/cli.js summary ctrf-reports/ctrf-report.json
      - name: Test historical
        run: node dist/core/cli.js historical ctrf-reports/ctrf-report.json --annotate false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test suite folded
        run: node dist/core/cli.js suite-folded ctrf-reports/ctrf-report.json --annotate false
      - name: Test failed
        run: node dist/core/cli.js failed ctrf-reports/ctrf-report.json --annotate false
      - name: Test failed rate
        run: node dist/core/cli.js failed-rate ctrf-reports/ctrf-report.json --annotate false --title "Failed rate"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test failed folded
        run: node dist/core/cli.js failed-folded ctrf-reports/ctrf-report.json --annotate false
      - name: Test flaky
        run: node dist/core/cli.js flaky ctrf-reports/ctrf-report.json --annotate false
      - name: Test flaky rate
        run: node dist/core/cli.js flaky-rate ctrf-reports/ctrf-report.json --annotate false --title "Flaky rate"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test ai
        run: node dist/core/cli.js ai ctrf-reports/ctrf-report.json --annotate false
      - name: Test skipped
        run: node dist/core/cli.js skipped ctrf-reports/ctrf-report.json --annotate false
      - name: Test custom summary
        run: node dist/core/cli.js custom ctrf-reports/ctrf-report.json templates/custom-summary.hbs --annotate false
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: ctrf-report
          path: ctrf-reports/ctrf-report.json
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: custom-artifact-name
          path: ctrf-reports/ctrf-report-no-fails.json
