name: Testing

on:
  push:
    branches:
      - '**'
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  pull_request:

permissions:
  pull-requests: write

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Format
        run: npm run format:check
      - name: Test
        run: npm run test
      - name: Publish Test Report
        uses: ./
        with:
          report-path: './ctrf/*.json'
          summary-report: true
          previous-results-report: true
          flaky-rate-report: true
          fail-rate-report: true
          pull-request-report: true
          upload-artifact: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
